# Text Mining

In this project we would explore the methods of preprocessing text which includes:
- BOW (Bag-of-Words)
- TF-IDF
- Word2Vec
- OneHotEncoding
- GloVe
- FastText

## Import Libraries

In [1]:
# Common Python Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os
from copy import deepcopy

# Text preprocessing/cleaning Libraries
import nltk
import re
import string
import contractions
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer # or LancasterStemmer, RegexpStemmer, SnowballStemmer
from nltk.tokenize import word_tokenize, sent_tokenize

# Bag of Words Libraries
from sklearn.feature_extraction.text  import CountVectorizer

# TF-IDF libraries
from sklearn.feature_extraction.text import TfidfVectorizer

# Word2Vec Libraries
import gensim
from gensim.models import Word2Vec

# GloVe Libraries

# Data Preprocessing Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Model Evaluation
from sklearn.metrics import f1_score, classification_report, confusion_matrix

## Import the data

In [2]:
text_data_path = "./train_data.csv"
text_data = pd.read_csv(text_data_path, sep = ",")

In [3]:
# View the data
text_data.head()

text  label
0  Here are Thursday's biggest analyst calls: App...      0
1  Buy Las Vegas Sands as travel to Singapore bui...      0
2  Piper Sandler downgrades DocuSign to sell, cit...      0
3  Analysts react to Tesla's latest earnings, bre...      0
4  Netflix and its peers are set for a ‘return to...      0

In [4]:
# text_data["label"].value_counts()

## Text Cleaning

text cleaning pipiline [source](https://stackoverflow.com/questions/48865150/pipeline-for-text-cleaning-processing-in-python)

In [5]:
def clean_text(text: str, language: str, tokenize: bool = False, remove_stop_words: bool = False, stem_words: bool = False):
    """
    This function is to clean the text from stopwords, punctuation and return a clean text for further analysis

    Args:
        text (str):
            The dataframe containing the text data
        
        language (str):
            This are the available languages:
            - "catalan": "ca"
            - "czech": "cs"
            - "german": "de"
            - "greek": "el"mlaskjdlj
            - "english": "en"
            - "spanish": "es"
            - "finnish": "fi"
            - "french": "fr"
            - "hungarian": "hu"
            - "icelandic": "is"
            - "italian": "it"
            - "latvian": "lv"
            - "dutch": "nl"
            - "polish": "pl"
            - "portuguese": "pt"
            - "romanian": "ro"
            - "russian": "ru"
            - "slovak": "sk"
            - "slovenian": "sl"
            - "swedish": "sv"
            - "tamil": "ta"
        
        tokenize (bool):
            True = return tokenized data
            False = return untokenized data
        
        remove_stop_words (bool):
            True = remove stop words
            False = do not remove stop words

        stem_words (bool):
            True = get the base words (i.e. spraying -> spray)
            False = leave the words as is
    """

    stemmer = PorterStemmer()
    stop_words = set(stopwords.words(language))

    def tokenize_text(text):
        return [w for s in sent_tokenize(text) for w in word_tokenize(s)]
    
    def remove_special_characters(text, characters=string.punctuation.replace('-', '')):
        pattern = re.compile(f"[{re.escape(characters)}]")
        return pattern.sub("", text)

    def stem_text(tokens):
        return [stemmer.stem(t) for t in tokens]

    def remove_stopwords_func(tokens):
        return [w for w in tokens if w not in stop_words]

    # Clean process
    text = contractions.fix(text)                        # fixing contraction
    text = text.strip().lower()                          # lowercase + trim
    text = remove_special_characters(text)               # remove punctuation
    tokens = tokenize_text(text)                         # tokenize words

    if remove_stop_words:
        tokens = remove_stopwords_func(tokens)           # remove stopwords
        
    if stem_words:
        tokens = stem_text(tokens)                       # stemming

    if tokenize:
        return tokens                                    # return as tokens
    else:
        return " ".join(tokens)                          # return as string

In [6]:
# Test
sample = "I love the smell of freshly brewed coffee in the morning!"
cleaned = clean_text(sample, language="english", remove_stop_words=True, tokenize=False)
print(cleaned)

love smell freshly brewed coffee morning


## Train Test Split

In [7]:
test_size = 0.20
val_size = 0.10

# Splitting the data into train and temp (which will be further split into validation and test)
train_df, test_df = train_test_split(text_data, test_size=test_size, stratify=text_data['label'], random_state=42) #stratify is used to ensure that the same proportion of each class is present in both the training and test sets

# Splitting train into validation and test sets
train_df, val_df = train_test_split(train_df, test_size=val_size, stratify=train_df['label'], random_state=42)

In [8]:
train_df.columns

Index(['text', 'label'], dtype='object')

In [9]:

# Spit the data to x and y values
x_train, y_train = train_df["text"], train_df["label"]
x_test, y_test = test_df["text"], test_df["label"]
x_val, y_val = val_df["text"], val_df["label"]

## Text Preprocessing Methods

### Bag-of-Words

Briefly, the bag-of-words preprocessing method only counts the occurence of each word and does not care about the ordering of the words.

**Example**

Both of these sentences become almost the same for BoW:

- “Coffee is life”
- “Life is coffee”

BoW doesn’t care that the word order is swapped — it just notes that both have “coffee”, “is”, and “life”.

In [10]:
bow_vectorizer = CountVectorizer(max_features=10000)  # you can change this limit
X_train_bow = bow_vectorizer.fit_transform(x_train)
X_test_bow = bow_vectorizer.transform(x_test)
X_val_bow = bow_vectorizer.transform(x_val)

In [11]:
print("Vocabulary size:", len(bow_vectorizer.get_feature_names_out()))
print("BoW shape (train):", X_train_bow.shape)
print("BoW shape (test):", X_test_bow.shape)
print("BoW shape (val):", X_val_bow.shape)

Vocabulary size: 10000
BoW shape (train): (12232, 10000)
BoW shape (test): (3398, 10000)
BoW shape (val): (1360, 10000)


### TF-IDF

TF-IDF or Term Frequency – Inverse Document Frequency.

It’s a way to represent how **important** a word is within a document, compared to the whole dataset (all documents).

1. Term Frequency (TF)
Formula:
$$
TF(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d}
$$

<br>

2. Inverse Document Frequency
$$
IDF(t) = \log{\frac{N}{n_t}}
$$
- $N$ = total number of documents
- $n_t$ = number of documents containing the term t

3. Combine TF-IDF
$$
\text{TF-IDF} = TF(t, d) × IDF(t)
$$

$Example:$

Let’s say you have 3 documents:
1. "coffee coffee bean taste nice"
2. "i love coffee"
3. "tea taste nice"

The word coffee appears often in doc1 and doc2, but not in doc3 → quite important!

The word taste appears in doc1 and doc3 → less special.

The word nice appears in doc1 and doc3 → also common.

In [12]:
tfidf_vectorizer = TfidfVectorizer(max_features=10000)  # you can change this limit
X_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
X_test_tfidf = tfidf_vectorizer.transform(x_test)
X_val_tfidf = tfidf_vectorizer.transform(x_val)

In [13]:
print("Vocabulary size:", len(tfidf_vectorizer.get_feature_names_out()))
print("tfidf shape (train):", X_train_tfidf.shape)
print("tfidf shape (test):", X_test_tfidf.shape)
print("tfidf shape (val):", X_val_tfidf.shape)

Vocabulary size: 10000
tfidf shape (train): (12232, 10000)
tfidf shape (test): (3398, 10000)
tfidf shape (val): (1360, 10000)


### Word2Vec

In [14]:
w2v_x_train = deepcopy(pd.DataFrame(x_train))
w2v_x_test = deepcopy(pd.DataFrame(x_test))
w2v_x_val = deepcopy(pd.DataFrame(x_val))
w2v_x_train

text
10369  Carmakers registered the fewest new vehicles i...
5022   Credit Spread Improvement And A Quick Update O...
1542   MOGU Files Annual Report on Form 20-F for Fisc...
6774   $GMAB: Genmab announces net sales of DARZALEX ...
11076  Swiss Producer &amp; Import Prices (M/M) Jun: ...
...                                                  ...
4964   $FOMC - Fomo reports Q1 results  https://t.co/...
15379  $ULH - Universal Logistics Holdings: Recent St...
5977   China’s banking regulator has asked lenders to...
6323   Quarles Says Fed Should Have Hiked Rates Befor...
6747   $BMI: Badger Meter beats by $0.05, beats on re...

[12232 rows x 1 columns]

In [15]:
w2v_x_train["tokenized"] = w2v_x_train["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)
w2v_x_test["tokenized"] = w2v_x_test["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)
w2v_x_val["tokenized"] = w2v_x_val["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)



In [16]:
w2v_x_train

text  \
10369  Carmakers registered the fewest new vehicles i...   
5022   Credit Spread Improvement And A Quick Update O...   
1542   MOGU Files Annual Report on Form 20-F for Fisc...   
6774   $GMAB: Genmab announces net sales of DARZALEX ...   
11076  Swiss Producer &amp; Import Prices (M/M) Jun: ...   
...                                                  ...   
4964   $FOMC - Fomo reports Q1 results  https://t.co/...   
15379  $ULH - Universal Logistics Holdings: Recent St...   
5977   China’s banking regulator has asked lenders to...   
6323   Quarles Says Fed Should Have Hiked Rates Befor...   
6747   $BMI: Badger Meter beats by $0.05, beats on re...   

                                               tokenized  
10369  [carmakers, registered, fewest, new, vehicles,...  
5022   [credit, spread, improvement, quick, update, s...  
1542   [mogu, files, annual, report, form, 20-f, fisc...  
6774   [gmab, genmab, announces, net, sales, darzalex...  
11076  [swiss, producer, amp, import, prices, mm, jun...  
...                                                  ...  
4964   [fomc, -, fomo, reports, q1, results, httpstco...  
15379  [ulh, -, universal, logistics, holdings, recen...  
5977   [china, ’, banking, regulator, asked, lenders,...  
6323   [quarles, says, fed, hiked, rates, taper, fini...  
6747   [bmi, badger, meter, beats, 005, beats, revs, ...  

[12232 rows x 2 columns]

In [17]:
# make the tokenized text into one list of tokens for word2vec to learn
train_tokenized_word_list = w2v_x_train["tokenized"].to_list()
test_tokenized_word_list = w2v_x_test["tokenized"].to_list()
val_tokenized_word_list = w2v_x_val["tokenized"].to_list()

In [18]:
# Train the word2vec odel
w2v_model = Word2Vec(
    sentences=train_tokenized_word_list,
    vector_size=100,
    window=5, # Max distance from target word
    min_count=2,
    sg=1, # use skip gram (0 for CBOW)
    workers=-1 #all cores to train
)

In [19]:
# Vectorize the text data after tokenizing the text
def sentence_vector(tokens, model):
    valid_words = [w for w in tokens if w in model.wv]
    if not valid_words:
        return np.zeros(model.vector_size)
    return np.mean(model.wv[valid_words], axis=0)

In [20]:
w2v_x_train["vectorized"] = w2v_x_train["tokenized"].apply(
    lambda x: sentence_vector(x, w2v_model)
)

w2v_x_test["vectorized"] = w2v_x_test["tokenized"].apply(
    lambda x: sentence_vector(x, w2v_model)
)

w2v_x_val["vectorized"] = w2v_x_val["tokenized"].apply(
    lambda x: sentence_vector(x, w2v_model)
)

In [21]:
w2v_x_train

text  \
10369  Carmakers registered the fewest new vehicles i...   
5022   Credit Spread Improvement And A Quick Update O...   
1542   MOGU Files Annual Report on Form 20-F for Fisc...   
6774   $GMAB: Genmab announces net sales of DARZALEX ...   
11076  Swiss Producer &amp; Import Prices (M/M) Jun: ...   
...                                                  ...   
4964   $FOMC - Fomo reports Q1 results  https://t.co/...   
15379  $ULH - Universal Logistics Holdings: Recent St...   
5977   China’s banking regulator has asked lenders to...   
6323   Quarles Says Fed Should Have Hiked Rates Befor...   
6747   $BMI: Badger Meter beats by $0.05, beats on re...   

                                               tokenized  \
10369  [carmakers, registered, fewest, new, vehicles,...   
5022   [credit, spread, improvement, quick, update, s...   
1542   [mogu, files, annual, report, form, 20-f, fisc...   
6774   [gmab, genmab, announces, net, sales, darzalex...   
11076  [swiss, producer, amp, import, prices, mm, jun...   
...                                                  ...   
4964   [fomc, -, fomo, reports, q1, results, httpstco...   
15379  [ulh, -, universal, logistics, holdings, recen...   
5977   [china, ’, banking, regulator, asked, lenders,...   
6323   [quarles, says, fed, hiked, rates, taper, fini...   
6747   [bmi, badger, meter, beats, 005, beats, revs, ...   

                                              vectorized  
10369  [-0.0037967074, 0.0020488119, 0.0005077503, 0....  
5022   [0.0019219258, 0.0017877818, 0.0005140198, 0.0...  
1542   [-5.4733526e-05, -9.8319724e-05, -0.0039652335...  
6774   [-0.0016815005, 0.00077633763, 0.0009391241, -...  
11076  [-0.0027268182, 0.0018887662, -0.0022556628, 0...  
...                                                  ...  
4964   [0.0005459329, 0.003093831, 0.00016384262, 0.0...  
15379  [0.0026075242, -0.001720027, 0.0039549335, 0.0...  
5977   [-0.00028046552, -0.00025583737, 0.0007133113,...  
6323   [-0.0011883086, 0.001673927, 0.002254193, -0.0...  
6747   [0.0018431159, -0.001166786, 0.00426564, -0.00...  

[12232 rows x 3 columns]

In [22]:
# Get the vectors and make it into a 2D array
# [[a, b, c], # label 1
#  [d, e, f], # label 2
#  [g, h, i], # label 3
#  ...      ,
#  [., ., .]] # label n

X_train_vec = np.vstack(w2v_x_train["vectorized"].values)
X_test_vec  = np.vstack(w2v_x_test["vectorized"].values)
X_val_vec   = np.vstack(w2v_x_val["vectorized"].values)

In [23]:
X_train_vec

array([[-3.79670737e-03,  2.04881188e-03,  5.07750316e-04, ...,
        -2.52123550e-03, -2.58323317e-03,  6.75106945e-04],
       [ 1.92192581e-03,  1.78778183e-03,  5.14019805e-04, ...,
         2.38531432e-03, -7.66813697e-04,  1.48879190e-04],
       [-5.47335258e-05, -9.83197242e-05, -3.96523345e-03, ...,
         2.04864264e-04,  3.85582773e-03, -4.04579332e-03],
       ...,
       [-2.80465523e-04, -2.55837367e-04,  7.13311310e-04, ...,
         6.00262021e-04, -2.73436162e-04,  1.23293675e-03],
       [-1.18830858e-03,  1.67392695e-03,  2.25419295e-03, ...,
         3.07700131e-04, -4.26686514e-04,  2.30513909e-03],
       [ 1.84311590e-03, -1.16678595e-03,  4.26563993e-03, ...,
         3.60934786e-03, -1.26184896e-03,  1.23401149e-03]])

### One-Hot-Encoding

In [24]:
# Create the vectorizer
vectorizer = CountVectorizer(binary=True)  # binary=True = one-hot style

# Fit and transform the sentences
x_train_ohe = vectorizer.fit_transform(x_train)
x_test_ohe = vectorizer.fit_transform(x_test)
x_val_ohe = vectorizer.fit_transform(x_val)

In [25]:
# Show result
print(vectorizer.get_feature_names_out())
print(x_train_ohe.toarray())

['00' '000' '000x' ... 'zwiyhkfxxj' 'zynx' 'zz9ugvmizx']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Pretrained Models

We will implement GloVe and FastText

### GloVe

Steps in using GloVe:
1. Preprocess and clean the text (already did it above)
    - (lowercase, remove punctuation, stopwords, etc.)

2. Tokenize the text
    - turn sentences into lists of words.

3. Build the vocabulary
    - list of all unique words in your dataset.

4. Download GloVe pretrained model
    - e.g. glove.6B.100d.txt from Stanford.
    - How to Download:
        - Linux:
            
            ```curl https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip -o glove_models.zip```
        - Windows:
            
            ```wget https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip```

5. Load GloVe embeddings
    - read the file into a dictionary:
<br>    { "coffee": [0.1, 0.3, ...], "dog": [-0.2, 0.4, ...] }

6. Create the embedding matrix
    - match each word in your vocabulary with its GloVe vector.
Words not found in GloVe get a zero vector or random small values.

#### Tokenize the Text

In [26]:
# Tokenizing the text
gloVe_x_train = deepcopy(pd.DataFrame(x_train))
gloVe_x_test = deepcopy(pd.DataFrame(x_test))
gloVe_x_val = deepcopy(pd.DataFrame(x_val))
gloVe_x_train

gloVe_x_train["tokenized"] = gloVe_x_train["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)
gloVe_x_test["tokenized"] = gloVe_x_test["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)
gloVe_x_val["tokenized"] = gloVe_x_val["text"].apply(
    lambda x: clean_text(
        text=x, 
        language="english",
        tokenize=True,
        remove_stop_words=True
    )
)

#### Build Vocabulary

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# get the tokenized text and make it into a list
gloVe_x_train_whole_text = gloVe_x_train["tokenized"].to_list()

gloVe_tokenizer = Tokenizer(num_words=20000) #this keeps only the most frequent 20000 words, you can change the number of words limit depending on how much RAM you have.
gloVe_tokenizer.fit_on_texts(gloVe_x_train_whole_text)

print("Number of unique words in dictionary =", len(gloVe_tokenizer.word_index))
print("Dictionary is =", gloVe_tokenizer.word_index)

Number of unique words in dictionary = 36132
Dictionary is = {'-': 1, '’': 2, '2022': 3, 'new': 4, 'earnings': 5, 'stocks': 6, 'economy': 7, 'inflation': 8, 'markets': 9, 'us': 10, 'business': 11, 'trading': 12, 'says': 13, 'results': 14, 'announces': 15, 'q2': 16, 'finance': 17, 'quarter': 18, 'bank': 19, 'second': 20, 'stockmarket': 21, 'investing': 22, 'market': 23, 'yous': 24, 'year': 25, 'first': 26, 'call': 27, 'energy': 28, 'uk': 29, 'prices': 30, 'china': 31, 'company': 32, 'stock': 33, 'global': 34, '“': 35, 'financial': 36, '”': 37, 'president': 38, 'rate': 39, 'may': 40, 'growth': 41, 'investors': 42, 'june': 43, 'revenue': 44, 'next': 45, 'billion': 46, 'could': 47, 'report': 48, 'gas': 49, 'oil': 50, 'ceo': 51, 'inc': 52, 'via': 53, 'amp': 54, 'dividend': 55, 'group': 56, 'one': 57, 'week': 58, 'high': 59, 'time': 60, 'beats': 61, 'fed': 62, 'price': 63, 'reports': 64, 'said': 65, 'economic': 66, 'sales': 67, 'shares': 68, 'data': 69, 'eps': 70, 'top': 71, 'buy': 72, 'acco